using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SyMath;

namespace Circuit
{
    /// <summary>
    /// Ideal voltage source.
    /// </summary>
    [CategoryAttribute("Standard")]
    [DisplayName("Rail")]
    public class Rail : OneTerminal
    {
        /// <summary>
        /// Expression for voltage V.
        /// </summary>
        private Quantity voltage = new Quantity(1, Units.V);
        [Description("Voltage generated by this voltage source.")]
        [Serialize]
        public Quantity Voltage { get { return voltage; } set { if (voltage.Set(value)) NotifyChanged("Voltage"); } }
        
        public Rail() { Name = "V1"; }
        
        public override void Analyze(ModifiedNodalAnalysis Mna)
        {
            Mna.AddTerminal(Terminal, Mna.AddNewUnknown("i" + Name));

            Mna.AddEquation(V, Voltage.Value);
        }

        public override void LayoutSymbol(SymbolLayout Sym)
        {
            base.LayoutSymbol(Sym);

            Sym.InBounds(new Coord(-20, 20), new Coord(20, 0));
            Sym.AddLine(EdgeType.Black, new Coord(-15, 0), new Coord(15, 0));
            Sym.DrawText(() => Voltage.ToString(), new Point(0, 2), Alignment.Center, Alignment.Near);
        }

        public override string ToString() { return Name + " = " + Voltage.ToString(); }
    }
}

