using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SyMath;
using System.ComponentModel;

namespace Circuit
{
    /// <summary>
    /// Ideal voltage source.
    /// </summary>
    [CategoryAttribute("Standard")]
    [DisplayName("Voltage Source")]
    public class VoltageSource : TwoTerminal
    {
        /// <summary>
        /// Expression for voltage V.
        /// </summary>
        private Quantity v = new Quantity(Call.Sin(t), Units.V);
        [Description("Voltage generated by this voltage source as a function of time t.")]
        [SchematicPersistent]
        public Quantity V { get { return v; } set { if (v.Set(value)) NotifyChanged("V"); } }

        public VoltageSource() { Name = "V1"; }
        public VoltageSource(Expression V) : this() { v.Value = V; }

        public override void Analyze(IList<Equal> Kcl, IList<Expression> Unknowns)
        {
            Anode.i = Call.New(ExprFunction.New("i_" + Name, t), t);
            Cathode.i = -Anode.i;

            Kcl.Add(Equal.New(Anode.V - Cathode.V, V.Value));
            Unknowns.Add(Anode.i);
        }

        protected override void DrawSymbol(SymbolLayout Sym)
        {
            int r = 10;

            Sym.AddWire(Anode, new Coord(0, r));
            Sym.AddWire(Cathode, new Coord(0, -r));

            Sym.AddCircle(ShapeType.Black, new Coord(0, 0), r);
            Sym.DrawPositive(ShapeType.Black, new Coord(0, 7));
            Sym.DrawNegative(ShapeType.Black, new Coord(0, -7));
            if (!(v.Value is Constant))
                Sym.DrawFunction(
                    ShapeType.Black, 
                    (t) => t * r * 0.75,
                    (t) => Math.Sin(t * 3.1415) * r * 0.5, -1, 1);
            Sym.DrawText(v.ToString(), new CoordD(r * 0.7, r * 0.7), Alignment.Near, Alignment.Near); 

            Sym.DrawText(Name, new CoordD(r * 0.7, r * -0.7), Alignment.Near, Alignment.Far); 
        }
    }
}

