name: Test
on:
- push
- pull_request
- workflow_dispatch
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-dotnet@v2
        with:
          # https://dotnet.microsoft.com/en-us/download/dotnet
          dotnet-version: |
            6.0.x
            8.0.x
      - name: Test LiveSPICE build
        shell: pwsh
        working-directory: LiveSPICE
        run: dotnet publish -c Release --framework net6.0-windows /p:DebugType=None /p:UseSharedCompilation=false  /p:UseRazorBuildServer=false
      - name: Test LiveSPICEVst build
        shell: pwsh
        working-directory: LiveSPICEVst
        run: dotnet publish -c Release --framework net6.0-windows /p:DebugType=None /p:UseSharedCompilation=false  /p:UseRazorBuildServer=false
      - name: Run circuit tests
        shell: pwsh
        working-directory: Tests
        run: dotnet run -c Release --framework net6.0-windows test "Circuits\*.schx"
      - name: Run examples
        shell: pwsh
        working-directory: Tests
        run: dotnet run -c Release --framework net6.0-windows test "Examples\*.schx"
